#version: "3.8"
services:
#  db:
#    image: postgres:13
#    container_name: skillgap-db
#    restart: always
#    ports:
#      - "5400:5432"
#    environment:
#      POSTGRES_USER: hardik
#      POSTGRES_PASSWORD: hardik
#      POSTGRES_DB: skillgapdb
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  postgres:
    image: postgres:13
    #    network_mode: host
    restart: always
    ports:
      - "5400:5432"  # 👈 This exposes the container port 5432 to localhost:5432
    environment:
      POSTGRES_USER: hardik
      POSTGRES_PASSWORD: hardik
      POSTGRES_DB: skillgapdb
#    depends_on:
#      - db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../apps/backend
    container_name: skillgap-backend
#    network_mode: host
#    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DB_USER: hardik
      DB_PASS: hardik
      DB_NAME: skillgapdb
      DB_HOST: postgres
      DB_PORT: 5432
      LANGGRAPH_URL: http://langgraph:9090
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - postgres

  langgraph:
    build: ../apps/agentic-core
    container_name: skillgap-ai
    environment:
      MODEL: mistral
      OLLAMA_URL: http://host.docker.internal:11434  # 🔥 internal Docker hostname
    ports:
      - "9090:9090"
    depends_on:
      - backend

  frontend:
    build: ../apps/frontend
    container_name: skillgap-ui
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - langgraph

volumes:
  pgdata:
